# Generated by Django 5.0.4 on 2025-04-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
    ]
